default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: buscador
  password: 

development:
  <<: *default
  database: buscador_development

test:
  <<: *default
  database: buscador_test
